#!/usr/bin/env zsh
# ~/.zshrc — bootstrap only (managed by chezmoi)

#
# Path settings
#
typeset -gU path fpath
path=(
    $path
    /usr/local/{,s}bin(N-/)
    ${HOME}/.local/bin(N-/)
    ${HOME}/.local/bin/common(N-/)
)
fpath=(
    $fpath
    ${HOME}/.local/bin/common(N-/)
)

# --------------------------------------------------
# Machine-local pre profile
# --------------------------------------------------
if [[ -f "$HOME/.pre_profile" ]]; then
  source "$HOME/.pre_profile"
fi

# --------------------------------------------------
# ZDOTDIR setup
# --------------------------------------------------
export ZDOTDIR="$HOME/.zsh"

# --------------------------------------------------
# Load real zsh configuration
# --------------------------------------------------
if [[ -f "$ZDOTDIR/zshrc" ]]; then
  source "$ZDOTDIR/zshrc"
fi

# --------------------------------------------------
# Machine-local post profile
# --------------------------------------------------
if [[ -f "$HOME/.post_profile" ]]; then
  source "$HOME/.post_profile"
fi


# --------------------------------------------------
# Load post-configuration (after all plugins)
# --------------------------------------------------
if [[ -f "$ZDOTDIR/zshrc.post.zsh" ]]; then
  source "$ZDOTDIR/zshrc.post.zsh"
fi

# ---------------------- END -----------------------