#!/usr/bin/env zsh
# $ZDOTDIR/.zshrc — bootstrap only (managed by chezmoi)

#
# Path settings
#
typeset -gU path fpath
path=(
    ${HOME}/.local/bin(N-/)
    ${HOME}/.local/bin/common(N-/)
    ${HOME}/.local/bin/macos(N-/)
    $path
    /usr/local/{,s}bin(N-/)
)
fpath=(
    $fpath
    ${HOME}/.local/share/zsh/completions(N-/)
)

# --------------------------------------------------
# Machine-local pre profile
# --------------------------------------------------
if [[ -f "$HOME/.pre_profile" ]]; then
  source "$HOME/.pre_profile"
fi

# --------------------------------------------------
# Load real zsh configuration
# --------------------------------------------------
if [[ -f "$ZDOTDIR/zshrc" ]]; then
  source "$ZDOTDIR/zshrc"
fi

# --------------------------------------------------
# Machine-local post profile
# --------------------------------------------------
if [[ -f "$HOME/.post_profile" ]]; then
  source "$HOME/.post_profile"
fi

# ---------------------- END -----------------------
