#!/usr/bin/env zsh
# $ZDOTDIR/.zshrc — bootstrap only (managed by chezmoi)

#
# Completion path
#
typeset -gU fpath
fpath=(
    $fpath
    ${HOME}/.local/share/zsh/completions(N-/)
)

# --------------------------------------------------
# Machine-local pre profile
# --------------------------------------------------
if [[ -f "$HOME/.zshrc.pre" ]]; then
  source "$HOME/.zshrc.pre"
fi

# --------------------------------------------------
# Load real zsh configuration
# --------------------------------------------------
if [[ -f "$ZDOTDIR/zshrc" ]]; then
  source "$ZDOTDIR/zshrc"
fi

# --------------------------------------------------
# Machine-local post profile
# --------------------------------------------------
if [[ -f "$HOME/.zshrc" ]]; then
  source "$HOME/.zshrc"
fi

# ---------------------- END -----------------------
